# docker-compose.yml
version: "3"
services:
  app:
    build: ./server
    command: ["yarn","start"]
    environment:
      NODE_ENV: production
      SECRET_KEY: visquares_rivan
      TWILIO_ACCOUNT_SID: ACd4015497e64bce3c54e5717c16783490
      TWILIO_AUTH_TOKEN: 8dcefe550e5c6379d481d3ec6de7196d
      SERVICE_SID: VAe20afe6a66288bd5426a83c3b530c4f4
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure
      endpoint_mode: vip
    depends_on:
      - postgres
    expose:
      - "4000"
    networks:
      - overlay
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - overlay
  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: visquare
      POSTGRES_PASSWORD: visquare123
      POSTGRES_DB: oilthentic_production
    ports:
      - "5432:5432"
    networks:
      - overlay
    volumes:
      - /home/ubuntu/postgresql/data:/var/lib/postgresql/data
networks:
  overlay: